export const PHONE_COUNTRY_CODES = [
  { code: '+212', flag: '🇲🇦', name: 'Morocco', pattern: /^\+212\s?\d{9}$/, example: '+212 6XX XXX XXX', digits: 9 },
  { code: '+213', flag: '🇩🇿', name: 'Algeria', pattern: /^\+213\s?\d{9}$/, example: '+213 5XX XX XX XX', digits: 9 },
  { code: '+216', flag: '🇹🇳', name: 'Tunisia', pattern: /^\+216\s?\d{8}$/, example: '+216 XX XXX XXX', digits: 8 },
  { code: '+218', flag: '🇱🇾', name: 'Libya', pattern: /^\+218\s?\d{9}$/, example: '+218 9X XXX XXXX', digits: 9 },
  { code: '+20', flag: '🇪🇬', name: 'Egypt', pattern: /^\+20\s?\d{10}$/, example: '+20 1XX XXX XXXX', digits: 10 },
  { code: '+221', flag: '🇸🇳', name: 'Senegal', pattern: /^\+221\s?\d{9}$/, example: '+221 7X XXX XX XX', digits: 9 },
  { code: '+225', flag: '🇨🇮', name: 'Côte d’Ivoire', pattern: /^\+225\s?\d{10}$/, example: '+225 0X XX XX XX XX', digits: 10 },
  { code: '+226', flag: '🇧🇫', name: 'Burkina Faso', pattern: /^\+226\s?\d{8}$/, example: '+226 XX XX XX XX', digits: 8 },
  { code: '+227', flag: '🇳🇪', name: 'Niger', pattern: /^\+227\s?\d{8}$/, example: '+227 XX XX XX XX', digits: 8 },
  { code: '+228', flag: '🇹🇬', name: 'Togo', pattern: /^\+228\s?\d{8}$/, example: '+228 XX XX XX XX', digits: 8 },
  { code: '+229', flag: '🇧🇯', name: 'Benin', pattern: /^\+229\s?\d{8}$/, example: '+229 XX XX XX XX', digits: 8 },
  { code: '+230', flag: '🇲🇺', name: 'Mauritius', pattern: /^\+230\s?\d{8}$/, example: '+230 XXXX XXXX', digits: 8 },
  { code: '+231', flag: '🇱🇷', name: 'Liberia', pattern: /^\+231\s?\d{8}$/, example: '+231 XX XXX XXX', digits: 8 },
  { code: '+232', flag: '🇸🇱', name: 'Sierra Leone', pattern: /^\+232\s?\d{8}$/, example: '+232 XX XXX XXX', digits: 8 },
  { code: '+233', flag: '🇬🇭', name: 'Ghana', pattern: /^\+233\s?\d{9}$/, example: '+233 XX XXX XXXX', digits: 9 },
  { code: '+234', flag: '🇳🇬', name: 'Nigeria', pattern: /^\+234\s?\d{10}$/, example: '+234 8XX XXX XXXX', digits: 10 },
  { code: '+235', flag: '🇹🇩', name: 'Chad', pattern: /^\+235\s?\d{8}$/, example: '+235 XX XX XX XX', digits: 8 },
  { code: '+237', flag: '🇨🇲', name: 'Cameroon', pattern: /^\+237\s?\d{9}$/, example: '+237 6XX XX XX XX', digits: 9 },
  { code: '+240', flag: '🇬🇶', name: 'Equatorial Guinea', pattern: /^\+240\s?\d{9}$/, example: '+240 XXX XXX XXX', digits: 9 },
  { code: '+241', flag: '🇬🇦', name: 'Gabon', pattern: /^\+241\s?\d{8}$/, example: '+241 XX XX XX XX', digits: 8 },
  { code: '+243', flag: '🇨🇩', name: 'DR Congo', pattern: /^\+243\s?\d{9}$/, example: '+243 XXX XXX XXX', digits: 9 },
  { code: '+250', flag: '🇷🇼', name: 'Rwanda', pattern: /^\+250\s?\d{9}$/, example: '+250 7XX XXX XXX', digits: 9 },
  { code: '+251', flag: '🇪🇹', name: 'Ethiopia', pattern: /^\+251\s?\d{9}$/, example: '+251 9XX XXX XXX', digits: 9 },
  { code: '+254', flag: '🇰🇪', name: 'Kenya', pattern: /^\+254\s?\d{9}$/, example: '+254 7XX XXX XXX', digits: 9 },
  { code: '+255', flag: '🇹🇿', name: 'Tanzania', pattern: /^\+255\s?\d{9}$/, example: '+255 7XX XXX XXX', digits: 9 },
  { code: '+256', flag: '🇺🇬', name: 'Uganda', pattern: /^\+256\s?\d{9}$/, example: '+256 7XX XXX XXX', digits: 9 },
  { code: '+260', flag: '🇿🇲', name: 'Zambia', pattern: /^\+260\s?\d{9}$/, example: '+260 9XX XXX XXX', digits: 9 },
  { code: '+263', flag: '🇿🇼', name: 'Zimbabwe', pattern: /^\+263\s?\d{9}$/, example: '+263 7X XXX XXXX', digits: 9 },
  { code: '+27', flag: '🇿🇦', name: 'South Africa', pattern: /^\+27\s?\d{9}$/, example: '+27 XX XXX XXXX', digits: 9 },
  { code: '+30', flag: '🇬🇷', name: 'Greece', pattern: /^\+30\s?\d{10}$/, example: '+30 69X XXX XXXX', digits: 10 },
  { code: '+31', flag: '🇳🇱', name: 'Netherlands', pattern: /^\+31\s?\d{9}$/, example: '+31 6 XXXX XXXX', digits: 9 },
  { code: '+32', flag: '🇧🇪', name: 'Belgium', pattern: /^\+32\s?\d{9}$/, example: '+32 4XX XX XX XX', digits: 9 },
  { code: '+33', flag: '🇫🇷', name: 'France', pattern: /^\+33\s?\d{9}$/, example: '+33 1 XX XX XX XX', digits: 9 },
  { code: '+34', flag: '🇪🇸', name: 'Spain', pattern: /^\+34\s?\d{9}$/, example: '+34 6XX XXX XXX', digits: 9 },
  { code: '+39', flag: '🇮🇹', name: 'Italy', pattern: /^\+39\s?\d{10}$/, example: '+39 3XX XXX XXXX', digits: 10 },
  { code: '+40', flag: '🇷🇴', name: 'Romania', pattern: /^\+40\s?\d{9}$/, example: '+40 7XX XXX XXX', digits: 9 },
  { code: '+41', flag: '🇨🇭', name: 'Switzerland', pattern: /^\+41\s?\d{9}$/, example: '+41 7X XXX XX XX', digits: 9 },
  { code: '+43', flag: '🇦🇹', name: 'Austria', pattern: /^\+43\s?\d{10}$/, example: '+43 6XX XXX XXXX', digits: 10 },
  { code: '+44', flag: '🇬🇧', name: 'United Kingdom', pattern: /^\+44\s?\d{10}$/, example: '+44 7XXX XXX XXX', digits: 10 },
  { code: '+45', flag: '🇩🇰', name: 'Denmark', pattern: /^\+45\s?\d{8}$/, example: '+45 XX XX XX XX', digits: 8 },
  { code: '+46', flag: '🇸🇪', name: 'Sweden', pattern: /^\+46\s?\d{9}$/, example: '+46 7XX XXX XXX', digits: 9 },
  { code: '+47', flag: '🇳🇴', name: 'Norway', pattern: /^\+47\s?\d{8}$/, example: '+47 XXX XX XXX', digits: 8 },
  { code: '+48', flag: '🇵🇱', name: 'Poland', pattern: /^\+48\s?\d{9}$/, example: '+48 XXX XXX XXX', digits: 9 },
  { code: '+49', flag: '🇩🇪', name: 'Germany', pattern: /^\+49\s?\d{10}$/, example: '+49 1XX XXX XXXX', digits: 10 },
  { code: '+351', flag: '🇵🇹', name: 'Portugal', pattern: /^\+351\s?\d{9}$/, example: '+351 9XX XXX XXX', digits: 9 },
  { code: '+352', flag: '🇱🇺', name: 'Luxembourg', pattern: /^\+352\s?\d{9}$/, example: '+352 6XX XXX XXX', digits: 9 },
  { code: '+353', flag: '🇮🇪', name: 'Ireland', pattern: /^\+353\s?\d{9}$/, example: '+353 8X XXX XXXX', digits: 9 },
  { code: '+354', flag: '🇮🇸', name: 'Iceland', pattern: /^\+354\s?\d{7}$/, example: '+354 XXX XXXX', digits: 7 },
  { code: '+358', flag: '🇫🇮', name: 'Finland', pattern: /^\+358\s?\d{9}$/, example: '+358 4X XXX XXXX', digits: 9 },
  { code: '+36', flag: '🇭🇺', name: 'Hungary', pattern: /^\+36\s?\d{9}$/, example: '+36 2X XXX XXXX', digits: 9 },
  { code: '+370', flag: '🇱🇹', name: 'Lithuania', pattern: /^\+370\s?\d{8}$/, example: '+370 6XX XXXXX', digits: 8 },
  { code: '+371', flag: '🇱🇻', name: 'Latvia', pattern: /^\+371\s?\d{8}$/, example: '+371 2XXXXXXX', digits: 8 },
  { code: '+372', flag: '🇪🇪', name: 'Estonia', pattern: /^\+372\s?\d{8}$/, example: '+372 5XXX XXXX', digits: 8 },
  { code: '+380', flag: '🇺🇦', name: 'Ukraine', pattern: /^\+380\s?\d{9}$/, example: '+380 XX XXX XXXX', digits: 9 },
  { code: '+385', flag: '🇭🇷', name: 'Croatia', pattern: /^\+385\s?\d{9}$/, example: '+385 9X XXX XXXX', digits: 9 },
  { code: '+386', flag: '🇸🇮', name: 'Slovenia', pattern: /^\+386\s?\d{8}$/, example: '+386 3X XXX XXX', digits: 8 },
  { code: '+420', flag: '🇨🇿', name: 'Czech Republic', pattern: /^\+420\s?\d{9}$/, example: '+420 XXX XXX XXX', digits: 9 },
  { code: '+421', flag: '🇸🇰', name: 'Slovakia', pattern: /^\+421\s?\d{9}$/, example: '+421 9XX XXX XXX', digits: 9 },
  { code: '+7', flag: '🇷🇺', name: 'Russia / Kazakhstan', pattern: /^\+7\s?\d{10}$/, example: '+7 XXX XXX XXXX', digits: 10 },
  { code: '+1', flag: '🇺🇸', name: 'United States / Canada', pattern: /^\+1\s?\d{10}$/, example: '+1 XXX XXX XXXX', digits: 10 },
  { code: '+52', flag: '🇲🇽', name: 'Mexico', pattern: /^\+52\s?\d{10}$/, example: '+52 XXX XXX XXXX', digits: 10 },
  { code: '+54', flag: '🇦🇷', name: 'Argentina', pattern: /^\+54\s?\d{10}$/, example: '+54 XX XXXX XXXX', digits: 10 },
  { code: '+55', flag: '🇧🇷', name: 'Brazil', pattern: /^\+55\s?\d{11}$/, example: '+55 XX XXXXX XXXX', digits: 11 },
  { code: '+56', flag: '🇨🇱', name: 'Chile', pattern: /^\+56\s?\d{9}$/, example: '+56 9 XXXX XXXX', digits: 9 },
  { code: '+57', flag: '🇨🇴', name: 'Colombia', pattern: /^\+57\s?\d{10}$/, example: '+57 3XX XXX XXXX', digits: 10 },
  { code: '+58', flag: '🇻🇪', name: 'Venezuela', pattern: /^\+58\s?\d{10}$/, example: '+58 4XX XXX XXXX', digits: 10 },
  { code: '+60', flag: '🇲🇾', name: 'Malaysia', pattern: /^\+60\s?\d{9}$/, example: '+60 1X XXX XXXX', digits: 9 },
  { code: '+61', flag: '🇦🇺', name: 'Australia', pattern: /^\+61\s?\d{9}$/, example: '+61 4XX XXX XXX', digits: 9 },
  { code: '+62', flag: '🇮🇩', name: 'Indonesia', pattern: /^\+62\s?\d{10}$/, example: '+62 8XX XXX XXXX', digits: 10 },
  { code: '+63', flag: '🇵🇭', name: 'Philippines', pattern: /^\+63\s?\d{10}$/, example: '+63 9XX XXX XXXX', digits: 10 },
  { code: '+64', flag: '🇳🇿', name: 'New Zealand', pattern: /^\+64\s?\d{9}$/, example: '+64 2X XXX XXXX', digits: 9 },
  { code: '+65', flag: '🇸🇬', name: 'Singapore', pattern: /^\+65\s?\d{8}$/, example: '+65 XXXX XXXX', digits: 8 },
  { code: '+66', flag: '🇹🇭', name: 'Thailand', pattern: /^\+66\s?\d{9}$/, example: '+66 8X XXX XXXX', digits: 9 },
  { code: '+81', flag: '🇯🇵', name: 'Japan', pattern: /^\+81\s?\d{10}$/, example: '+81 90 XXXX XXXX', digits: 10 },
  { code: '+82', flag: '🇰🇷', name: 'South Korea', pattern: /^\+82\s?\d{10}$/, example: '+82 10 XXXX XXXX', digits: 10 },
  { code: '+84', flag: '🇻🇳', name: 'Vietnam', pattern: /^\+84\s?\d{9}$/, example: '+84 9XX XXX XXX', digits: 9 },
  { code: '+86', flag: '🇨🇳', name: 'China', pattern: /^\+86\s?\d{11}$/, example: '+86 1XX XXXX XXXX', digits: 11 },
  { code: '+91', flag: '🇮🇳', name: 'India', pattern: /^\+91\s?\d{10}$/, example: '+91 XXXXX XXXXX', digits: 10 },
  { code: '+92', flag: '🇵🇰', name: 'Pakistan', pattern: /^\+92\s?\d{10}$/, example: '+92 3XX XXX XXXX', digits: 10 },
  { code: '+98', flag: '🇮🇷', name: 'Iran', pattern: /^\+98\s?\d{10}$/, example: '+98 9XX XXX XXXX', digits: 10 },
  { code: '+90', flag: '🇹🇷', name: 'Turkey', pattern: /^\+90\s?\d{10}$/, example: '+90 5XX XXX XXXX', digits: 10 },
  { code: '+93', flag: '🇦🇫', name: 'Afghanistan', pattern: /^\+93\s?\d{9}$/, example: '+93 7XX XXX XXX', digits: 9 },
  { code: '+94', flag: '🇱🇰', name: 'Sri Lanka', pattern: /^\+94\s?\d{9}$/, example: '+94 7X XXX XXXX', digits: 9 },
  { code: '+95', flag: '🇲🇲', name: 'Myanmar', pattern: /^\+95\s?\d{9}$/, example: '+95 9XX XXX XXX', digits: 9 },
  { code: '+960', flag: '🇲🇻', name: 'Maldives', pattern: /^\+960\s?\d{7}$/, example: '+960 XXX XXXX', digits: 7 },
  { code: '+961', flag: '🇱🇧', name: 'Lebanon', pattern: /^\+961\s?\d{8}$/, example: '+961 XX XXX XXX', digits: 8 },
  { code: '+962', flag: '🇯🇴', name: 'Jordan', pattern: /^\+962\s?\d{9}$/, example: '+962 7X XXX XXXX', digits: 9 },
  { code: '+963', flag: '🇸🇾', name: 'Syria', pattern: /^\+963\s?\d{9}$/, example: '+963 9XX XXX XXX', digits: 9 },
  { code: '+964', flag: '🇮🇶', name: 'Iraq', pattern: /^\+964\s?\d{10}$/, example: '+964 7XX XXX XXXX', digits: 10 },
  { code: '+965', flag: '🇰🇼', name: 'Kuwait', pattern: /^\+965\s?\d{8}$/, example: '+965 XXXX XXXX', digits: 8 },
  { code: '+966', flag: '🇸🇦', name: 'Saudi Arabia', pattern: /^\+966\s?\d{9}$/, example: '+966 5X XXX XXXX', digits: 9 },
  { code: '+967', flag: '🇾🇪', name: 'Yemen', pattern: /^\+967\s?\d{9}$/, example: '+967 7XX XXX XXX', digits: 9 },
  { code: '+968', flag: '🇴🇲', name: 'Oman', pattern: /^\+968\s?\d{8}$/, example: '+968 XXXX XXXX', digits: 8 },
  { code: '+970', flag: '🇵🇸', name: 'Palestine', pattern: /^\+970\s?\d{9}$/, example: '+970 5XX XXX XXX', digits: 9 },
  { code: '+971', flag: '🇦🇪', name: 'United Arab Emirates', pattern: /^\+971\s?\d{9}$/, example: '+971 5X XXX XXXX', digits: 9 },
  { code: '+972', flag: '🇮🇱', name: 'Israel', pattern: /^\+972\s?\d{9}$/, example: '+972 5X XXX XXXX', digits: 9 },
  { code: '+973', flag: '🇧🇭', name: 'Bahrain', pattern: /^\+973\s?\d{8}$/, example: '+973 XXXX XXXX', digits: 8 },
  { code: '+974', flag: '🇶🇦', name: 'Qatar', pattern: /^\+974\s?\d{8}$/, example: '+974 XXXX XXXX', digits: 8 },
  { code: '+975', flag: '🇧🇹', name: 'Bhutan', pattern: /^\+975\s?\d{8}$/, example: '+975 17XX XXXX', digits: 8 },
  { code: '+976', flag: '🇲🇳', name: 'Mongolia', pattern: /^\+976\s?\d{8}$/, example: '+976 XXXX XXXX', digits: 8 },
  { code: '+977', flag: '🇳🇵', name: 'Nepal', pattern: /^\+977\s?\d{10}$/, example: '+977 98X XXX XXXX', digits: 10 },
  { code: '+992', flag: '🇹🇯', name: 'Tajikistan', pattern: /^\+992\s?\d{9}$/, example: '+992 XX XXX XXXX', digits: 9 },
  { code: '+993', flag: '🇹🇲', name: 'Turkmenistan', pattern: /^\+993\s?\d{8}$/, example: '+993 XX XXX XXX', digits: 8 },
  { code: '+994', flag: '🇦🇿', name: 'Azerbaijan', pattern: /^\+994\s?\d{9}$/, example: '+994 XX XXX XX XX', digits: 9 },
  { code: '+995', flag: '🇬🇪', name: 'Georgia', pattern: /^\+995\s?\d{9}$/, example: '+995 5XX XX XX XX', digits: 9 },
  { code: '+996', flag: '🇰🇬', name: 'Kyrgyzstan', pattern: /^\+996\s?\d{9}$/, example: '+996 XXX XXX XXX', digits: 9 },
  { code: '+998', flag: '🇺🇿', name: 'Uzbekistan', pattern: /^\+998\s?\d{9}$/, example: '+998 XX XXX XXXX', digits: 9 },
];
